/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbortedMessageResponse
 */
export interface AbortedMessageResponse {
    /**
     * 
     * @type {string}
     * @memberof AbortedMessageResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof AbortedMessageResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the AbortedMessageResponse interface.
 */
export function instanceOfAbortedMessageResponse(value: object): boolean {
    return true;
}

export function AbortedMessageResponseFromJSON(json: any): AbortedMessageResponse {
    return AbortedMessageResponseFromJSONTyped(json, false);
}

export function AbortedMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbortedMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AbortedMessageResponseToJSON(value?: AbortedMessageResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

