/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Any
 */
export interface Any {
    [key: string]: object | any;
    /**
     * 
     * @type {string}
     * @memberof Any
     */
    type?: string;
}

/**
 * Check if a given object implements the Any interface.
 */
export function instanceOfAny(value: object): boolean {
    return true;
}

export function AnyFromJSON(json: any): Any {
    return AnyFromJSONTyped(json, false);
}

export function AnyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Any {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'type': json['@type'] == null ? undefined : json['@type'],
    };
}

export function AnyToJSON(value?: Any | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        '@type': value['type'],
    };
}

