/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssertionTupleKey } from './AssertionTupleKey';
import {
    AssertionTupleKeyFromJSON,
    AssertionTupleKeyFromJSONTyped,
    AssertionTupleKeyToJSON,
} from './AssertionTupleKey';

/**
 * 
 * @export
 * @interface Assertion
 */
export interface Assertion {
    /**
     * 
     * @type {AssertionTupleKey}
     * @memberof Assertion
     */
    tupleKey: AssertionTupleKey;
    /**
     * 
     * @type {boolean}
     * @memberof Assertion
     */
    expectation: boolean;
}

/**
 * Check if a given object implements the Assertion interface.
 */
export function instanceOfAssertion(value: object): boolean {
    if (!('tupleKey' in value)) return false;
    if (!('expectation' in value)) return false;
    return true;
}

export function AssertionFromJSON(json: any): Assertion {
    return AssertionFromJSONTyped(json, false);
}

export function AssertionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assertion {
    if (json == null) {
        return json;
    }
    return {
        
        'tupleKey': AssertionTupleKeyFromJSON(json['tuple_key']),
        'expectation': json['expectation'],
    };
}

export function AssertionToJSON(value?: Assertion | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tuple_key': AssertionTupleKeyToJSON(value['tupleKey']),
        'expectation': value['expectation'],
    };
}

