/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Condition } from './Condition';
import {
    ConditionFromJSON,
    ConditionFromJSONTyped,
    ConditionToJSON,
} from './Condition';
import type { TypeDefinition } from './TypeDefinition';
import {
    TypeDefinitionFromJSON,
    TypeDefinitionFromJSONTyped,
    TypeDefinitionToJSON,
} from './TypeDefinition';

/**
 * 
 * @export
 * @interface AuthorizationModel
 */
export interface AuthorizationModel {
    /**
     * 
     * @type {string}
     * @memberof AuthorizationModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorizationModel
     */
    schemaVersion: string;
    /**
     * 
     * @type {Array<TypeDefinition>}
     * @memberof AuthorizationModel
     */
    typeDefinitions: Array<TypeDefinition>;
    /**
     * 
     * @type {{ [key: string]: Condition; }}
     * @memberof AuthorizationModel
     */
    conditions?: { [key: string]: Condition; };
}

/**
 * Check if a given object implements the AuthorizationModel interface.
 */
export function instanceOfAuthorizationModel(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('schemaVersion' in value)) return false;
    if (!('typeDefinitions' in value)) return false;
    return true;
}

export function AuthorizationModelFromJSON(json: any): AuthorizationModel {
    return AuthorizationModelFromJSONTyped(json, false);
}

export function AuthorizationModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizationModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'schemaVersion': json['schema_version'],
        'typeDefinitions': ((json['type_definitions'] as Array<any>).map(TypeDefinitionFromJSON)),
        'conditions': json['conditions'] == null ? undefined : (mapValues(json['conditions'], ConditionFromJSON)),
    };
}

export function AuthorizationModelToJSON(value?: AuthorizationModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'schema_version': value['schemaVersion'],
        'type_definitions': ((value['typeDefinitions'] as Array<any>).map(TypeDefinitionToJSON)),
        'conditions': value['conditions'] == null ? undefined : (mapValues(value['conditions'], ConditionToJSON)),
    };
}

