/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckRequestTupleKey
 */
export interface CheckRequestTupleKey {
    /**
     * 
     * @type {string}
     * @memberof CheckRequestTupleKey
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof CheckRequestTupleKey
     */
    relation: string;
    /**
     * 
     * @type {string}
     * @memberof CheckRequestTupleKey
     */
    object: string;
}

/**
 * Check if a given object implements the CheckRequestTupleKey interface.
 */
export function instanceOfCheckRequestTupleKey(value: object): boolean {
    if (!('user' in value)) return false;
    if (!('relation' in value)) return false;
    if (!('object' in value)) return false;
    return true;
}

export function CheckRequestTupleKeyFromJSON(json: any): CheckRequestTupleKey {
    return CheckRequestTupleKeyFromJSONTyped(json, false);
}

export function CheckRequestTupleKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckRequestTupleKey {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'],
        'relation': json['relation'],
        'object': json['object'],
    };
}

export function CheckRequestTupleKeyToJSON(value?: CheckRequestTupleKey | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': value['user'],
        'relation': value['relation'],
        'object': value['object'],
    };
}

