/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckRequestTupleKey } from './CheckRequestTupleKey';
import {
    CheckRequestTupleKeyFromJSON,
    CheckRequestTupleKeyFromJSONTyped,
    CheckRequestTupleKeyToJSON,
} from './CheckRequestTupleKey';
import type { ContextualTupleKeys } from './ContextualTupleKeys';
import {
    ContextualTupleKeysFromJSON,
    ContextualTupleKeysFromJSONTyped,
    ContextualTupleKeysToJSON,
} from './ContextualTupleKeys';

/**
 * 
 * @export
 * @interface CheckRequest
 */
export interface CheckRequest {
    /**
     * 
     * @type {CheckRequestTupleKey}
     * @memberof CheckRequest
     */
    tupleKey: CheckRequestTupleKey;
    /**
     * 
     * @type {ContextualTupleKeys}
     * @memberof CheckRequest
     */
    contextualTuples?: ContextualTupleKeys;
    /**
     * 
     * @type {string}
     * @memberof CheckRequest
     */
    authorizationModelId?: string;
    /**
     * Defaults to false. Making it true has performance implications.
     * @type {boolean}
     * @memberof CheckRequest
     */
    readonly trace?: boolean;
    /**
     * Additional request context that will be used to evaluate any ABAC conditions encountered
     * in the query evaluation.
     * @type {object}
     * @memberof CheckRequest
     */
    context?: object;
}

/**
 * Check if a given object implements the CheckRequest interface.
 */
export function instanceOfCheckRequest(value: object): boolean {
    if (!('tupleKey' in value)) return false;
    return true;
}

export function CheckRequestFromJSON(json: any): CheckRequest {
    return CheckRequestFromJSONTyped(json, false);
}

export function CheckRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tupleKey': CheckRequestTupleKeyFromJSON(json['tuple_key']),
        'contextualTuples': json['contextual_tuples'] == null ? undefined : ContextualTupleKeysFromJSON(json['contextual_tuples']),
        'authorizationModelId': json['authorization_model_id'] == null ? undefined : json['authorization_model_id'],
        'trace': json['trace'] == null ? undefined : json['trace'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function CheckRequestToJSON(value?: CheckRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tuple_key': CheckRequestTupleKeyToJSON(value['tupleKey']),
        'contextual_tuples': ContextualTupleKeysToJSON(value['contextualTuples']),
        'authorization_model_id': value['authorizationModelId'],
        'context': value['context'],
    };
}

