/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckResponse
 */
export interface CheckResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CheckResponse
     */
    allowed?: boolean;
    /**
     * For internal use only.
     * @type {string}
     * @memberof CheckResponse
     */
    resolution?: string;
}

/**
 * Check if a given object implements the CheckResponse interface.
 */
export function instanceOfCheckResponse(value: object): boolean {
    return true;
}

export function CheckResponseFromJSON(json: any): CheckResponse {
    return CheckResponseFromJSONTyped(json, false);
}

export function CheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'allowed': json['allowed'] == null ? undefined : json['allowed'],
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
    };
}

export function CheckResponseToJSON(value?: CheckResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'allowed': value['allowed'],
        'resolution': value['resolution'],
    };
}

