/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Computed
 */
export interface Computed {
    /**
     * 
     * @type {string}
     * @memberof Computed
     */
    userset: string;
}

/**
 * Check if a given object implements the Computed interface.
 */
export function instanceOfComputed(value: object): boolean {
    if (!('userset' in value)) return false;
    return true;
}

export function ComputedFromJSON(json: any): Computed {
    return ComputedFromJSONTyped(json, false);
}

export function ComputedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Computed {
    if (json == null) {
        return json;
    }
    return {
        
        'userset': json['userset'],
    };
}

export function ComputedToJSON(value?: Computed | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userset': value['userset'],
    };
}

