/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SourceInfo } from './SourceInfo';
import {
    SourceInfoFromJSON,
    SourceInfoFromJSONTyped,
    SourceInfoToJSON,
} from './SourceInfo';

/**
 * 
 * @export
 * @interface ConditionMetadata
 */
export interface ConditionMetadata {
    /**
     * 
     * @type {string}
     * @memberof ConditionMetadata
     */
    module?: string;
    /**
     * 
     * @type {SourceInfo}
     * @memberof ConditionMetadata
     */
    sourceInfo?: SourceInfo;
}

/**
 * Check if a given object implements the ConditionMetadata interface.
 */
export function instanceOfConditionMetadata(value: object): boolean {
    return true;
}

export function ConditionMetadataFromJSON(json: any): ConditionMetadata {
    return ConditionMetadataFromJSONTyped(json, false);
}

export function ConditionMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConditionMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'module': json['module'] == null ? undefined : json['module'],
        'sourceInfo': json['source_info'] == null ? undefined : SourceInfoFromJSON(json['source_info']),
    };
}

export function ConditionMetadataToJSON(value?: ConditionMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'module': value['module'],
        'source_info': SourceInfoToJSON(value['sourceInfo']),
    };
}

