/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStoreRequest
 */
export interface CreateStoreRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateStoreRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateStoreRequest interface.
 */
export function instanceOfCreateStoreRequest(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function CreateStoreRequestFromJSON(json: any): CreateStoreRequest {
    return CreateStoreRequestFromJSONTyped(json, false);
}

export function CreateStoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateStoreRequestToJSON(value?: CreateStoreRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

