/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Userset } from './Userset';
import {
    UsersetFromJSON,
    UsersetFromJSONTyped,
    UsersetToJSON,
} from './Userset';

/**
 * 
 * @export
 * @interface Difference
 */
export interface Difference {
    /**
     * 
     * @type {Userset}
     * @memberof Difference
     */
    base: Userset;
    /**
     * 
     * @type {Userset}
     * @memberof Difference
     */
    subtract: Userset;
}

/**
 * Check if a given object implements the Difference interface.
 */
export function instanceOfDifference(value: object): boolean {
    if (!('base' in value)) return false;
    if (!('subtract' in value)) return false;
    return true;
}

export function DifferenceFromJSON(json: any): Difference {
    return DifferenceFromJSONTyped(json, false);
}

export function DifferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Difference {
    if (json == null) {
        return json;
    }
    return {
        
        'base': UsersetFromJSON(json['base']),
        'subtract': UsersetFromJSON(json['subtract']),
    };
}

export function DifferenceToJSON(value?: Difference | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'base': UsersetToJSON(value['base']),
        'subtract': UsersetToJSON(value['subtract']),
    };
}

