/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ErrorCode = {
    NoError: 'no_error',
    ValidationError: 'validation_error',
    AuthorizationModelNotFound: 'authorization_model_not_found',
    AuthorizationModelResolutionTooComplex: 'authorization_model_resolution_too_complex',
    InvalidWriteInput: 'invalid_write_input',
    CannotAllowDuplicateTuplesInOneRequest: 'cannot_allow_duplicate_tuples_in_one_request',
    CannotAllowDuplicateTypesInOneRequest: 'cannot_allow_duplicate_types_in_one_request',
    CannotAllowMultipleReferencesToOneRelation: 'cannot_allow_multiple_references_to_one_relation',
    InvalidContinuationToken: 'invalid_continuation_token',
    InvalidTupleSet: 'invalid_tuple_set',
    InvalidCheckInput: 'invalid_check_input',
    InvalidExpandInput: 'invalid_expand_input',
    UnsupportedUserSet: 'unsupported_user_set',
    InvalidObjectFormat: 'invalid_object_format',
    WriteFailedDueToInvalidInput: 'write_failed_due_to_invalid_input',
    AuthorizationModelAssertionsNotFound: 'authorization_model_assertions_not_found',
    LatestAuthorizationModelNotFound: 'latest_authorization_model_not_found',
    TypeNotFound: 'type_not_found',
    RelationNotFound: 'relation_not_found',
    EmptyRelationDefinition: 'empty_relation_definition',
    InvalidUser: 'invalid_user',
    InvalidTuple: 'invalid_tuple',
    UnknownRelation: 'unknown_relation',
    StoreIdInvalidLength: 'store_id_invalid_length',
    AssertionsTooManyItems: 'assertions_too_many_items',
    IdTooLong: 'id_too_long',
    AuthorizationModelIdTooLong: 'authorization_model_id_too_long',
    TupleKeyValueNotSpecified: 'tuple_key_value_not_specified',
    TupleKeysTooManyOrTooFewItems: 'tuple_keys_too_many_or_too_few_items',
    PageSizeInvalid: 'page_size_invalid',
    ParamMissingValue: 'param_missing_value',
    DifferenceBaseMissingValue: 'difference_base_missing_value',
    SubtractBaseMissingValue: 'subtract_base_missing_value',
    ObjectTooLong: 'object_too_long',
    RelationTooLong: 'relation_too_long',
    TypeDefinitionsTooFewItems: 'type_definitions_too_few_items',
    TypeInvalidLength: 'type_invalid_length',
    TypeInvalidPattern: 'type_invalid_pattern',
    RelationsTooFewItems: 'relations_too_few_items',
    RelationsTooLong: 'relations_too_long',
    RelationsInvalidPattern: 'relations_invalid_pattern',
    ObjectInvalidPattern: 'object_invalid_pattern',
    QueryStringTypeContinuationTokenMismatch: 'query_string_type_continuation_token_mismatch',
    ExceededEntityLimit: 'exceeded_entity_limit',
    InvalidContextualTuple: 'invalid_contextual_tuple',
    DuplicateContextualTuple: 'duplicate_contextual_tuple',
    InvalidAuthorizationModel: 'invalid_authorization_model',
    UnsupportedSchemaVersion: 'unsupported_schema_version'
} as const;
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export function instanceOfErrorCode(value: any): boolean {
    return Object.values(ErrorCode).includes(value);
}

export function ErrorCodeFromJSON(json: any): ErrorCode {
    return ErrorCodeFromJSONTyped(json, false);
}

export function ErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCode {
    return json as ErrorCode;
}

export function ErrorCodeToJSON(value?: ErrorCode | null): any {
    return value as any;
}

