/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExpandRequestTupleKey } from './ExpandRequestTupleKey';
import {
    ExpandRequestTupleKeyFromJSON,
    ExpandRequestTupleKeyFromJSONTyped,
    ExpandRequestTupleKeyToJSON,
} from './ExpandRequestTupleKey';

/**
 * 
 * @export
 * @interface ExpandRequest
 */
export interface ExpandRequest {
    /**
     * 
     * @type {ExpandRequestTupleKey}
     * @memberof ExpandRequest
     */
    tupleKey: ExpandRequestTupleKey;
    /**
     * 
     * @type {string}
     * @memberof ExpandRequest
     */
    authorizationModelId?: string;
}

/**
 * Check if a given object implements the ExpandRequest interface.
 */
export function instanceOfExpandRequest(value: object): boolean {
    if (!('tupleKey' in value)) return false;
    return true;
}

export function ExpandRequestFromJSON(json: any): ExpandRequest {
    return ExpandRequestFromJSONTyped(json, false);
}

export function ExpandRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpandRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tupleKey': ExpandRequestTupleKeyFromJSON(json['tuple_key']),
        'authorizationModelId': json['authorization_model_id'] == null ? undefined : json['authorization_model_id'],
    };
}

export function ExpandRequestToJSON(value?: ExpandRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tuple_key': ExpandRequestTupleKeyToJSON(value['tupleKey']),
        'authorization_model_id': value['authorizationModelId'],
    };
}

