/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsersetTree } from './UsersetTree';
import {
    UsersetTreeFromJSON,
    UsersetTreeFromJSONTyped,
    UsersetTreeToJSON,
} from './UsersetTree';

/**
 * 
 * @export
 * @interface ExpandResponse
 */
export interface ExpandResponse {
    /**
     * 
     * @type {UsersetTree}
     * @memberof ExpandResponse
     */
    tree?: UsersetTree;
}

/**
 * Check if a given object implements the ExpandResponse interface.
 */
export function instanceOfExpandResponse(value: object): boolean {
    return true;
}

export function ExpandResponseFromJSON(json: any): ExpandResponse {
    return ExpandResponseFromJSONTyped(json, false);
}

export function ExpandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpandResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tree': json['tree'] == null ? undefined : UsersetTreeFromJSON(json['tree']),
    };
}

export function ExpandResponseToJSON(value?: ExpandResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tree': UsersetTreeToJSON(value['tree']),
    };
}

