/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpandRequestTupleKey
 */
export interface ExpandRequestTupleKey {
    /**
     * 
     * @type {string}
     * @memberof ExpandRequestTupleKey
     */
    relation: string;
    /**
     * 
     * @type {string}
     * @memberof ExpandRequestTupleKey
     */
    object: string;
}

/**
 * Check if a given object implements the ExpandRequestTupleKey interface.
 */
export function instanceOfExpandRequestTupleKey(value: object): boolean {
    if (!('relation' in value)) return false;
    if (!('object' in value)) return false;
    return true;
}

export function ExpandRequestTupleKeyFromJSON(json: any): ExpandRequestTupleKey {
    return ExpandRequestTupleKeyFromJSONTyped(json, false);
}

export function ExpandRequestTupleKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpandRequestTupleKey {
    if (json == null) {
        return json;
    }
    return {
        
        'relation': json['relation'],
        'object': json['object'],
    };
}

export function ExpandRequestTupleKeyToJSON(value?: ExpandRequestTupleKey | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'relation': value['relation'],
        'object': value['object'],
    };
}

