/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalErrorCode } from './InternalErrorCode';
import {
    InternalErrorCodeFromJSON,
    InternalErrorCodeFromJSONTyped,
    InternalErrorCodeToJSON,
} from './InternalErrorCode';

/**
 * 
 * @export
 * @interface InternalErrorMessageResponse
 */
export interface InternalErrorMessageResponse {
    /**
     * 
     * @type {InternalErrorCode}
     * @memberof InternalErrorMessageResponse
     */
    code?: InternalErrorCode;
    /**
     * 
     * @type {string}
     * @memberof InternalErrorMessageResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the InternalErrorMessageResponse interface.
 */
export function instanceOfInternalErrorMessageResponse(value: object): boolean {
    return true;
}

export function InternalErrorMessageResponseFromJSON(json: any): InternalErrorMessageResponse {
    return InternalErrorMessageResponseFromJSONTyped(json, false);
}

export function InternalErrorMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalErrorMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : InternalErrorCodeFromJSON(json['code']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function InternalErrorMessageResponseToJSON(value?: InternalErrorMessageResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': InternalErrorCodeToJSON(value['code']),
        'message': value['message'],
    };
}

