/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListObjectsResponse
 */
export interface ListObjectsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ListObjectsResponse
     */
    objects: Array<string>;
}

/**
 * Check if a given object implements the ListObjectsResponse interface.
 */
export function instanceOfListObjectsResponse(value: object): boolean {
    if (!('objects' in value)) return false;
    return true;
}

export function ListObjectsResponseFromJSON(json: any): ListObjectsResponse {
    return ListObjectsResponseFromJSONTyped(json, false);
}

export function ListObjectsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListObjectsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'objects': json['objects'],
    };
}

export function ListObjectsResponseToJSON(value?: ListObjectsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'objects': value['objects'],
    };
}

