/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Node } from './Node';
import {
    NodeFromJSON,
    NodeFromJSONTyped,
    NodeToJSON,
} from './Node';

/**
 * 
 * @export
 * @interface Nodes
 */
export interface Nodes {
    /**
     * 
     * @type {Array<Node>}
     * @memberof Nodes
     */
    nodes: Array<Node>;
}

/**
 * Check if a given object implements the Nodes interface.
 */
export function instanceOfNodes(value: object): boolean {
    if (!('nodes' in value)) return false;
    return true;
}

export function NodesFromJSON(json: any): Nodes {
    return NodesFromJSONTyped(json, false);
}

export function NodesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Nodes {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': ((json['nodes'] as Array<any>).map(NodeFromJSON)),
    };
}

export function NodesToJSON(value?: Nodes | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nodes': ((value['nodes'] as Array<any>).map(NodeToJSON)),
    };
}

