/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectRelation
 */
export interface ObjectRelation {
    /**
     * 
     * @type {string}
     * @memberof ObjectRelation
     */
    object?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjectRelation
     */
    relation?: string;
}

/**
 * Check if a given object implements the ObjectRelation interface.
 */
export function instanceOfObjectRelation(value: object): boolean {
    return true;
}

export function ObjectRelationFromJSON(json: any): ObjectRelation {
    return ObjectRelationFromJSONTyped(json, false);
}

export function ObjectRelationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectRelation {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : json['object'],
        'relation': json['relation'] == null ? undefined : json['relation'],
    };
}

export function ObjectRelationToJSON(value?: ObjectRelation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'relation': value['relation'],
    };
}

