/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotFoundErrorCode } from './NotFoundErrorCode';
import {
    NotFoundErrorCodeFromJSON,
    NotFoundErrorCodeFromJSONTyped,
    NotFoundErrorCodeToJSON,
} from './NotFoundErrorCode';

/**
 * 
 * @export
 * @interface PathUnknownErrorMessageResponse
 */
export interface PathUnknownErrorMessageResponse {
    /**
     * 
     * @type {NotFoundErrorCode}
     * @memberof PathUnknownErrorMessageResponse
     */
    code?: NotFoundErrorCode;
    /**
     * 
     * @type {string}
     * @memberof PathUnknownErrorMessageResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the PathUnknownErrorMessageResponse interface.
 */
export function instanceOfPathUnknownErrorMessageResponse(value: object): boolean {
    return true;
}

export function PathUnknownErrorMessageResponseFromJSON(json: any): PathUnknownErrorMessageResponse {
    return PathUnknownErrorMessageResponseFromJSONTyped(json, false);
}

export function PathUnknownErrorMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PathUnknownErrorMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : NotFoundErrorCodeFromJSON(json['code']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function PathUnknownErrorMessageResponseToJSON(value?: PathUnknownErrorMessageResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': NotFoundErrorCodeToJSON(value['code']),
        'message': value['message'],
    };
}

