/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorizationModel } from './AuthorizationModel';
import {
    AuthorizationModelFromJSON,
    AuthorizationModelFromJSONTyped,
    AuthorizationModelToJSON,
} from './AuthorizationModel';

/**
 * 
 * @export
 * @interface ReadAuthorizationModelsResponse
 */
export interface ReadAuthorizationModelsResponse {
    /**
     * 
     * @type {Array<AuthorizationModel>}
     * @memberof ReadAuthorizationModelsResponse
     */
    authorizationModels: Array<AuthorizationModel>;
    /**
     * The continuation token will be empty if there are no more models.
     * @type {string}
     * @memberof ReadAuthorizationModelsResponse
     */
    continuationToken?: string;
}

/**
 * Check if a given object implements the ReadAuthorizationModelsResponse interface.
 */
export function instanceOfReadAuthorizationModelsResponse(value: object): boolean {
    if (!('authorizationModels' in value)) return false;
    return true;
}

export function ReadAuthorizationModelsResponseFromJSON(json: any): ReadAuthorizationModelsResponse {
    return ReadAuthorizationModelsResponseFromJSONTyped(json, false);
}

export function ReadAuthorizationModelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadAuthorizationModelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizationModels': ((json['authorization_models'] as Array<any>).map(AuthorizationModelFromJSON)),
        'continuationToken': json['continuation_token'] == null ? undefined : json['continuation_token'],
    };
}

export function ReadAuthorizationModelsResponseToJSON(value?: ReadAuthorizationModelsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'authorization_models': ((value['authorizationModels'] as Array<any>).map(AuthorizationModelToJSON)),
        'continuation_token': value['continuationToken'],
    };
}

