/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReadRequestTupleKey } from './ReadRequestTupleKey';
import {
    ReadRequestTupleKeyFromJSON,
    ReadRequestTupleKeyFromJSONTyped,
    ReadRequestTupleKeyToJSON,
} from './ReadRequestTupleKey';

/**
 * 
 * @export
 * @interface ReadRequest
 */
export interface ReadRequest {
    /**
     * 
     * @type {ReadRequestTupleKey}
     * @memberof ReadRequest
     */
    tupleKey?: ReadRequestTupleKey;
    /**
     * 
     * @type {number}
     * @memberof ReadRequest
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof ReadRequest
     */
    continuationToken?: string;
}

/**
 * Check if a given object implements the ReadRequest interface.
 */
export function instanceOfReadRequest(value: object): boolean {
    return true;
}

export function ReadRequestFromJSON(json: any): ReadRequest {
    return ReadRequestFromJSONTyped(json, false);
}

export function ReadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tupleKey': json['tuple_key'] == null ? undefined : ReadRequestTupleKeyFromJSON(json['tuple_key']),
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'continuationToken': json['continuation_token'] == null ? undefined : json['continuation_token'],
    };
}

export function ReadRequestToJSON(value?: ReadRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tuple_key': ReadRequestTupleKeyToJSON(value['tupleKey']),
        'page_size': value['pageSize'],
        'continuation_token': value['continuationToken'],
    };
}

