/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadRequestTupleKey
 */
export interface ReadRequestTupleKey {
    /**
     * 
     * @type {string}
     * @memberof ReadRequestTupleKey
     */
    user?: string;
    /**
     * 
     * @type {string}
     * @memberof ReadRequestTupleKey
     */
    relation?: string;
    /**
     * 
     * @type {string}
     * @memberof ReadRequestTupleKey
     */
    object?: string;
}

/**
 * Check if a given object implements the ReadRequestTupleKey interface.
 */
export function instanceOfReadRequestTupleKey(value: object): boolean {
    return true;
}

export function ReadRequestTupleKeyFromJSON(json: any): ReadRequestTupleKey {
    return ReadRequestTupleKeyFromJSONTyped(json, false);
}

export function ReadRequestTupleKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadRequestTupleKey {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : json['user'],
        'relation': json['relation'] == null ? undefined : json['relation'],
        'object': json['object'] == null ? undefined : json['object'],
    };
}

export function ReadRequestTupleKeyToJSON(value?: ReadRequestTupleKey | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': value['user'],
        'relation': value['relation'],
        'object': value['object'],
    };
}

