/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorizationModel } from './AuthorizationModel';
import {
    AuthorizationModelFromJSON,
    AuthorizationModelFromJSONTyped,
    AuthorizationModelToJSON,
} from './AuthorizationModel';

/**
 * 
 * @export
 * @interface ReadAuthorizationModelResponse
 */
export interface ReadAuthorizationModelResponse {
    /**
     * 
     * @type {AuthorizationModel}
     * @memberof ReadAuthorizationModelResponse
     */
    authorizationModel?: AuthorizationModel;
}

/**
 * Check if a given object implements the ReadAuthorizationModelResponse interface.
 */
export function instanceOfReadAuthorizationModelResponse(value: object): boolean {
    return true;
}

export function ReadAuthorizationModelResponseFromJSON(json: any): ReadAuthorizationModelResponse {
    return ReadAuthorizationModelResponseFromJSONTyped(json, false);
}

export function ReadAuthorizationModelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadAuthorizationModelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizationModel': json['authorization_model'] == null ? undefined : AuthorizationModelFromJSON(json['authorization_model']),
    };
}

export function ReadAuthorizationModelResponseToJSON(value?: ReadAuthorizationModelResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'authorization_model': AuthorizationModelToJSON(value['authorizationModel']),
    };
}

