/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceInfo
 */
export interface SourceInfo {
    /**
     * 
     * @type {string}
     * @memberof SourceInfo
     */
    file?: string;
}

/**
 * Check if a given object implements the SourceInfo interface.
 */
export function instanceOfSourceInfo(value: object): boolean {
    return true;
}

export function SourceInfoFromJSON(json: any): SourceInfo {
    return SourceInfoFromJSONTyped(json, false);
}

export function SourceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'] == null ? undefined : json['file'],
    };
}

export function SourceInfoToJSON(value?: SourceInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'file': value['file'],
    };
}

