/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationshipCondition } from './RelationshipCondition';
import {
    RelationshipConditionFromJSON,
    RelationshipConditionFromJSONTyped,
    RelationshipConditionToJSON,
} from './RelationshipCondition';

/**
 * 
 * @export
 * @interface TupleKey
 */
export interface TupleKey {
    /**
     * 
     * @type {string}
     * @memberof TupleKey
     */
    user: string;
    /**
     * 
     * @type {string}
     * @memberof TupleKey
     */
    relation: string;
    /**
     * 
     * @type {string}
     * @memberof TupleKey
     */
    object: string;
    /**
     * 
     * @type {RelationshipCondition}
     * @memberof TupleKey
     */
    condition?: RelationshipCondition;
}

/**
 * Check if a given object implements the TupleKey interface.
 */
export function instanceOfTupleKey(value: object): boolean {
    if (!('user' in value)) return false;
    if (!('relation' in value)) return false;
    if (!('object' in value)) return false;
    return true;
}

export function TupleKeyFromJSON(json: any): TupleKey {
    return TupleKeyFromJSONTyped(json, false);
}

export function TupleKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TupleKey {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'],
        'relation': json['relation'],
        'object': json['object'],
        'condition': json['condition'] == null ? undefined : RelationshipConditionFromJSON(json['condition']),
    };
}

export function TupleKeyToJSON(value?: TupleKey | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': value['user'],
        'relation': value['relation'],
        'object': value['object'],
        'condition': RelationshipConditionToJSON(value['condition']),
    };
}

