/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ObjectRelation } from './ObjectRelation';
import {
    ObjectRelationFromJSON,
    ObjectRelationFromJSONTyped,
    ObjectRelationToJSON,
} from './ObjectRelation';

/**
 * 
 * @export
 * @interface TupleToUserset
 */
export interface TupleToUserset {
    /**
     * 
     * @type {ObjectRelation}
     * @memberof TupleToUserset
     */
    tupleset: ObjectRelation;
    /**
     * 
     * @type {ObjectRelation}
     * @memberof TupleToUserset
     */
    computedUserset: ObjectRelation;
}

/**
 * Check if a given object implements the TupleToUserset interface.
 */
export function instanceOfTupleToUserset(value: object): boolean {
    if (!('tupleset' in value)) return false;
    if (!('computedUserset' in value)) return false;
    return true;
}

export function TupleToUsersetFromJSON(json: any): TupleToUserset {
    return TupleToUsersetFromJSONTyped(json, false);
}

export function TupleToUsersetFromJSONTyped(json: any, ignoreDiscriminator: boolean): TupleToUserset {
    if (json == null) {
        return json;
    }
    return {
        
        'tupleset': ObjectRelationFromJSON(json['tupleset']),
        'computedUserset': ObjectRelationFromJSON(json['computedUserset']),
    };
}

export function TupleToUsersetToJSON(value?: TupleToUserset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tupleset': ObjectRelationToJSON(value['tupleset']),
        'computedUserset': ObjectRelationToJSON(value['computedUserset']),
    };
}

