/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Node } from './Node';
import {
    NodeFromJSON,
    NodeFromJSONTyped,
    NodeToJSON,
} from './Node';

/**
 * 
 * @export
 * @interface UsersetTreeDifference
 */
export interface UsersetTreeDifference {
    /**
     * 
     * @type {Node}
     * @memberof UsersetTreeDifference
     */
    base: Node;
    /**
     * 
     * @type {Node}
     * @memberof UsersetTreeDifference
     */
    subtract: Node;
}

/**
 * Check if a given object implements the UsersetTreeDifference interface.
 */
export function instanceOfUsersetTreeDifference(value: object): boolean {
    if (!('base' in value)) return false;
    if (!('subtract' in value)) return false;
    return true;
}

export function UsersetTreeDifferenceFromJSON(json: any): UsersetTreeDifference {
    return UsersetTreeDifferenceFromJSONTyped(json, false);
}

export function UsersetTreeDifferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersetTreeDifference {
    if (json == null) {
        return json;
    }
    return {
        
        'base': NodeFromJSON(json['base']),
        'subtract': NodeFromJSON(json['subtract']),
    };
}

export function UsersetTreeDifferenceToJSON(value?: UsersetTreeDifference | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'base': NodeToJSON(value['base']),
        'subtract': NodeToJSON(value['subtract']),
    };
}

