/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Node } from './Node';
import {
    NodeFromJSON,
    NodeFromJSONTyped,
    NodeToJSON,
} from './Node';

/**
 * A UsersetTree contains the result of an Expansion.
 * @export
 * @interface UsersetTree
 */
export interface UsersetTree {
    /**
     * 
     * @type {Node}
     * @memberof UsersetTree
     */
    root?: Node;
}

/**
 * Check if a given object implements the UsersetTree interface.
 */
export function instanceOfUsersetTree(value: object): boolean {
    return true;
}

export function UsersetTreeFromJSON(json: any): UsersetTree {
    return UsersetTreeFromJSONTyped(json, false);
}

export function UsersetTreeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersetTree {
    if (json == null) {
        return json;
    }
    return {
        
        'root': json['root'] == null ? undefined : NodeFromJSON(json['root']),
    };
}

export function UsersetTreeToJSON(value?: UsersetTree | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'root': NodeToJSON(value['root']),
    };
}

