/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';

/**
 * 
 * @export
 * @interface ValidationErrorMessageResponse
 */
export interface ValidationErrorMessageResponse {
    /**
     * 
     * @type {ErrorCode}
     * @memberof ValidationErrorMessageResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorMessageResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the ValidationErrorMessageResponse interface.
 */
export function instanceOfValidationErrorMessageResponse(value: object): boolean {
    return true;
}

export function ValidationErrorMessageResponseFromJSON(json: any): ValidationErrorMessageResponse {
    return ValidationErrorMessageResponseFromJSONTyped(json, false);
}

export function ValidationErrorMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ValidationErrorMessageResponseToJSON(value?: ValidationErrorMessageResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': ErrorCodeToJSON(value['code']),
        'message': value['message'],
    };
}

