/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WriteRequestDeletes } from './WriteRequestDeletes';
import {
    WriteRequestDeletesFromJSON,
    WriteRequestDeletesFromJSONTyped,
    WriteRequestDeletesToJSON,
} from './WriteRequestDeletes';
import type { WriteRequestWrites } from './WriteRequestWrites';
import {
    WriteRequestWritesFromJSON,
    WriteRequestWritesFromJSONTyped,
    WriteRequestWritesToJSON,
} from './WriteRequestWrites';

/**
 * 
 * @export
 * @interface WriteRequest
 */
export interface WriteRequest {
    /**
     * 
     * @type {WriteRequestWrites}
     * @memberof WriteRequest
     */
    writes?: WriteRequestWrites;
    /**
     * 
     * @type {WriteRequestDeletes}
     * @memberof WriteRequest
     */
    deletes?: WriteRequestDeletes;
    /**
     * 
     * @type {string}
     * @memberof WriteRequest
     */
    authorizationModelId?: string;
}

/**
 * Check if a given object implements the WriteRequest interface.
 */
export function instanceOfWriteRequest(value: object): boolean {
    return true;
}

export function WriteRequestFromJSON(json: any): WriteRequest {
    return WriteRequestFromJSONTyped(json, false);
}

export function WriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'writes': json['writes'] == null ? undefined : WriteRequestWritesFromJSON(json['writes']),
        'deletes': json['deletes'] == null ? undefined : WriteRequestDeletesFromJSON(json['deletes']),
        'authorizationModelId': json['authorization_model_id'] == null ? undefined : json['authorization_model_id'],
    };
}

export function WriteRequestToJSON(value?: WriteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'writes': WriteRequestWritesToJSON(value['writes']),
        'deletes': WriteRequestDeletesToJSON(value['deletes']),
        'authorization_model_id': value['authorizationModelId'],
    };
}

