/* tslint:disable */
/* eslint-disable */
/**
 * OpenFGA
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: community@openfga.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriteAuthorizationModelResponse
 */
export interface WriteAuthorizationModelResponse {
    /**
     * 
     * @type {string}
     * @memberof WriteAuthorizationModelResponse
     */
    authorizationModelId: string;
}

/**
 * Check if a given object implements the WriteAuthorizationModelResponse interface.
 */
export function instanceOfWriteAuthorizationModelResponse(value: object): boolean {
    if (!('authorizationModelId' in value)) return false;
    return true;
}

export function WriteAuthorizationModelResponseFromJSON(json: any): WriteAuthorizationModelResponse {
    return WriteAuthorizationModelResponseFromJSONTyped(json, false);
}

export function WriteAuthorizationModelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteAuthorizationModelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizationModelId': json['authorization_model_id'],
    };
}

export function WriteAuthorizationModelResponseToJSON(value?: WriteAuthorizationModelResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'authorization_model_id': value['authorizationModelId'],
    };
}

